version: "3"
services:
  db:
    image: mysql:5.7
    restart: always
    command: --lower_case_table_names=1
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "test"
      MYSQL_DATABASE: "sample"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
      TZ: "Asia/Seoul"

    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./DB/:/var/lib/mysql