version: "3"
services:
    db:
        image: mcr.microsoft.com/mssql/server:2017-latest
        container_name: sqlserver
        ports:
            - "1433:1433"
        environment:
            ACCEPT_EULA: "Y"
            MSSQL_PID: "Developer"
            SA_PASSWORD: "qwe123!@#"
            default-character-set: "utf8mb4"
        volumes:
            - ./db:/var/opt/mssql
            - ./bakfile/data.bak:/Host_Data/SqlBakFile.BAK
